### ISSUE TITLE
Pillow was built without XCB support

### ISSUE THREAD

**Issue by phanirithvij** [ponty/pyscreenshot#78]
python
```
Python 3.8.2 (default, May 13 2020, 20:39:11) 
[GCC 6.3.0 20170516] on linux
```

```
Pillow in ./.local/lib/python3.8/site-packages (7.1.2)
pyscreenshot in ./.local/lib/python3.8/site-packages (2.2)
```
Os: Linux
```
Linux 4.15.0-30deepin-generic #31 SMP Fri Nov 30 04:29:02 UTC 2018 x86_64 GNU/Linux
```

Tried
```py
import pyscreenshot as ImageGrab
im = ImageGrab.grab(backend="pil")
```

Error is
```py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rithvij/.local/lib/python3.8/site-packages/pyscreenshot/__init__.py", line 31, in grab
    return backend_grab(backend, bbox, childprocess)
  File "/home/rithvij/.local/lib/python3.8/site-packages/pyscreenshot/loader.py", line 145, in backend_grab
    return force(backend, bbox, childprocess)
  File "/home/rithvij/.local/lib/python3.8/site-packages/pyscreenshot/loader.py", line 136, in force
    return childprocess_grab(backend_name, bbox)
  File "/home/rithvij/.local/lib/python3.8/site-packages/pyscreenshot/childproc.py", line 37, in childprocess_grab
    raise FailedBackendError(p)
pyscreenshot.err.FailedBackendError: <EasyProcess cmd_param=['/usr/local/bin/python3.8', '-m', 'pyscreenshot.cli.grab', '--filename', '/tmp/pyscreenshotxceu2y9p/screenshot.png', '--backend', 'pil'] cmd=['/usr/local/bin/python3.8', '-m', 'pyscreenshot.cli.grab', '--filename', '/tmp/pyscreenshotxceu2y9p/screenshot.png', '--backend', 'pil'] oserror=None return_code=1 stdout="" stderr="Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/rithvij/.local/lib/python3.8/site-packages/pyscreenshot/cli/grab.py", line 8, in <module>
    def main(filename="", bbox="", backend="", show=False):
  File "/home/rithvij/.local/lib/python3.8/site-packages/entrypoint2/__init__.py", line 436, in entrypoint
    return func(**kwargs)
  File "/home/rithvij/.local/lib/python3.8/site-packages/pyscreenshot/cli/grab.py", line 24, in main
    im = pyscreenshot.grab(bbox=bbox, childprocess=False, backend=backend)
  File "/home/rithvij/.local/lib/python3.8/site-packages/pyscreenshot/__init__.py", line 31, in grab
    return backend_grab(backend, bbox, childprocess)
  File "/home/rithvij/.local/lib/python3.8/site-packages/pyscreenshot/loader.py", line 145, in backend_grab
    return force(backend, bbox, childprocess)
  File "/home/rithvij/.local/lib/python3.8/site-packages/pyscreenshot/loader.py", line 139, in force
    im = obj.grab(bbox)
  File "/home/rithvij/.local/lib/python3.8/site-packages/pyscreenshot/plugins/pilwrap.py", line 17, in grab
    return ImageGrab.grab(bbox)
  File "/home/rithvij/.local/lib/python3.8/site-packages/PIL/ImageGrab.py", line 63, in grab
    raise IOError("Pillow was built without XCB support")
OSError: Pillow was built without XCB support" timeout_happened=False>
```

How can I resolve this?

**Comment by ponty** [comment]
`pyscreenshot` is only a wrapper.
Check Pillow without `pyscreenshot`:
```pycon
>>> from PIL import __version__
>>> print(__version__)
7.1.2
>>> from PIL import ImageGrab
>>> ImageGrab.grab()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/titi/.local/lib/python3.7/site-packages/PIL/ImageGrab.py", line 63, in grab
    raise IOError("Pillow was built without XCB support")
OSError: Pillow was built without XCB support
```
If you get the same error then this is not a pyscreenshot bug. 
I think you should ask the packager.

Pillow doc: https://pillow.readthedocs.io/en/latest/reference/ImageGrab.html

**Comment by phanirithvij** [comment]
Thanks

**Comment by ponty** [comment]
I also built Pillow from source and then it worked.

To make it clear: setting Pillow backend (`im = ImageGrab.grab(backend="pil")`) makes no sense.
If Pillow can take screenshots then pyscreenshot is not needed.
The backend was only implemented for testing.
